"""
This module contains the Pydantic models used for validating and serializing data
related to books in the system.

Models:
- Book: The basic book model that includes essential fields for a book.
- BookDetailModel: A more detailed model that includes reviews and tags associated with the book.
- BookCreateModel: A model used for creating a new book with necessary attributes.
- BookUpdateModel: A model used for updating existing book information.
"""

import uuid
from typing import List
from pydantic import BaseModel
from datetime import datetime, date

from src.tags.schemas import TagModel
from src.reviews.schemas import ReviewModel


class Book(BaseModel):
    """
    Represents a book entity with essential information.

    This is the base model used for representing a book in the system. It includes
    information about the book such as title, author, publisher, publication date,
    language, and the creation and update timestamps.

    Attributes:
        uid (uuid.UUID): A unique identifier for the book.
        title (str): The title of the book.
        author (str): The author of the book.
        publisher (str): The publisher of the book.
        published_date (date): The publication date of the book.
        page_count (int): The number of pages in the book.
        language (str): The language in which the book is written.
        created_at (datetime): The timestamp when the book was created in the system.
        updated_at (datetime): The timestamp when the book was last updated.
    """

    uid: uuid.UUID
    title: str
    author: str
    publisher: str
    published_date: date
    page_count: int
    language: str
    created_at: datetime
    updated_at: datetime


class BookDetailModel(Book):
    """
    A detailed representation of a book, including associated reviews and tags.

    This model extends the `Book` base model to include additional information like
    reviews and tags associated with the book. This is typically used when retrieving
    detailed book information, including user feedback and associated tags for categorization.

    Attributes:
        reviews (List[ReviewModel]): A list of reviews for the book.
        tags (List[TagModel]): A list of tags associated with the book, such as genres or topics.
    """

    reviews: List[ReviewModel]
    tags: List[TagModel]


class BookCreateModel(BaseModel):
    """
    A model used for creating a new book in the system.

    This model defines the required fields for creating a new book. It includes
    the essential attributes such as title, author, publisher, and other book
    details, but does not include the book's creation or update timestamps, as
    these will be automatically generated by the system.

    Attributes:
        title (str): The title of the book.
        author (str): The author of the book.
        publisher (str): The publisher of the book.
        published_date (date): The publication date of the book.
        page_count (int): The number of pages in the book.
        language (str): The language in which the book is written.
    """

    title: str
    author: str
    publisher: str
    published_date: date
    page_count: int
    language: str


class BookUpdateModel(BaseModel):
    """
    A model used for updating an existing book in the system.

    This model defines the fields that can be updated in an existing book record.
    It does not include the `uid`, `created_at`, or `updated_at` fields, as they
    are either fixed or automatically managed by the system.

    Attributes:
        title (str): The title of the book.
        author (str): The author of the book.
        publisher (str): The publisher of the book.
        page_count (int): The number of pages in the book.
        language (str): The language in which the book is written.
    """

    title: str
    author: str
    publisher: str
    page_count: int
    language: str
